### ISSUE TITLE
Twitch chat: custom bit emotes not always showing up?

### ISSUE THREAD

**Issue by jespk77** [jespk77/pyplayer#5]
channel bit emotes are not showing up in chat, the default ones do work

**Comment by jkr-77** [comment]
log is empty, the json file from twitch api has probably changed

**Comment by jkr-77** [comment]
seems to be working again? haven't changed anything

**Comment by jespk77** [comment]
not showing when it is at the end of a message

**Comment by jespk77** [comment]
expanded into new issue: https://github.com/jespk77/pyplayer/issues/13
